### ISSUE TITLE
Not an issue but more of a question

### ISSUE THREAD

**Issue by rmdy** [p-hather/FPLReminder#4]
Could you add the ability of checking Super 6 (https://super6.skysports.com/) and adding a reminder for that or a new script?

**Comment by p-hather** [comment]
Hey, thanks for the comment! That's a good idea but this is a personal project and I don't know enough about the game to make it worthwhile investing the time to be honest. That said, it could potentially be achieved using [this API](https://api.s6.sbgservices.com/v2/docs/) (if that's the right thing) so could be looked at in the future.
